repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: requirements-txt-fixer
  - id: check-docstring-first
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: double-quote-string-fixer
  - id: name-tests-test
- repo: https://github.com/timothycrosley/isort/
  rev: 4.3.21-2
  hooks:
  - id: isort
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.0
  hooks:
  - id: flake8
    args:
    - ./code/algorithm
    - ./code/tests
# Use local pylint hook for import resolution
# - repo: local
#   hooks:
#   - id: pylint
#     name: pylint
#     entry: pylint
#     language: system
#     types: [python]
#     args:
#     - ./code/algorithm
#     - ./code/tests
#     - --disable=similarities
- repo: https://github.com/PyCQA/pydocstyle
  rev: 5.0.2
  hooks:
  - id: pydocstyle
    args:
    - ./code/algorithm
    - ./code/tests
