repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: requirements-txt-fixer
  - id: check-docstring-first
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: double-quote-string-fixer
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.0
  hooks:
  - id: flake8
- repo: https://github.com/pycqa/pylint
  rev: pylint-2.5.2
  hooks:
  - id: pylint
    args:
    - ./code/algorithm
    - --disable=similarities
- repo: https://github.com/PyCQA/pydocstyle
  rev: 5.0.2
  hooks:
  - id: pydocstyle
    args:
    - ./code/algorithm
